// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;

namespace MyMachinePlatformClientCore.Models.Models.dbModels;
/// <summary>
/// 
/// </summary>
public partial class MMoCoreContext : DbContext
{
    public MMoCoreContext(DbContextOptions<MMoCoreContext> options)
        : base(options)
    {
    }
    /// <summary>
    /// 
    /// </summary>
    public virtual DbSet<Player> Players { get; set; }
    /// <summary>
    /// 
    /// </summary>
    /// <param name="modelBuilder"></param>
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        modelBuilder
            .UseCollation("utf8mb4_0900_ai_ci")
            .HasCharSet("utf8mb4");
        modelBuilder.Entity<Player>(entity =>
        {
            entity.HasKey(e => e.Id).HasName("PRIMARY");

            entity.ToTable("player");

            entity.Property(e => e.Password).HasMaxLength(255);
            entity.Property(e => e.TelPhone).HasMaxLength(255);
            entity.Property(e => e.UserName).HasMaxLength(255);
        });

        OnModelCreatingPartial(modelBuilder);
    }
    /// <summary>
    /// 
    /// </summary>
    /// <param name="optionsBuilder"></param>
    protected override void OnConfiguring(DbContextOptionsBuilder optionsBuilder)
    {
        //if (!optionsBuilder.IsConfigured)
        //{
        //    optionsBuilder.UseMySql(DBHelpConnectionString.ReadConfigInfo(), Microsoft.EntityFrameworkCore.ServerVersion.Parse("8.0.22-mysql"));
        //}
    }

    partial void OnModelCreatingPartial(ModelBuilder modelBuilder);


    
}